add new js and html file
KittySaur/card_game pull request #1
Opened 2022-06-10 23:14 UTC by KittySaur

2022-06-11 16:58 UTC, mrerberg requested changes

2022-06-11 16:58 UTC, mrerberg commented on js/script.js
> +levelButtons.forEach(button => {
Проще будет это сделать через всплытие

https://learn.javascript.ru/event-bubbling

2022-06-11 16:58 UTC, mrerberg commented on js/script.js
> +const levelButtons = levelForm.querySelectorAll('.level__choice');
Используй классы для стилизации, но логику лучше завязывать на id/data атрибуты. Классы слишком изменчивы

2022-06-16 07:30 UTC, mrerberg approved these changes

2022-06-18 22:23 UTC, KittySaur commented
Комментарии исправлены и уже не актуальны

2022-06-18 22:23 UTC, closed without merging