Fifth hw
KittySaur/card_game pull request #6
Opened 2022-07-03 20:06 UTC by KittySaur

4 и 5 дз вместе.
Дописана логика игры, добавлен typescript, исправлены ошибки с добавлением файлов в bundle.js

2022-07-04 07:07 UTC, mrerberg requested changes

2022-07-04 07:07 UTC, mrerberg commented on dist/game-screen.html
> +<!doctype html><html lang="ru"><head><meta charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="shortc
dist папки не должно быть в гите, удали ее пожалуйста и добавь в гит игнор

2022-07-04 07:07 UTC, mrerberg commented on src/js/game_screen.ts
> +const cardsField = document.getElementById('cards-field') as HTMLDivElement
Очень много as. as - крайний случай, это каст типов.

const cardsField: HTMLDivElement | null = document.getElementById('cards-field');

2022-07-04 07:07 UTC, mrerberg commented on src/js/game_screen.ts
> +        levelNumber = 3
level number не совсем подходящее название, переменная же хранит в себе количество пар карт?

2022-07-04 07:07 UTC, mrerberg commented on src/js/game_screen.ts
> +    if (level === 'medium') {
Значение уровней сложности я бы вынес в программные константы 

```js
const LEVEL_MEDIUM = 'medium';
...

```

2022-07-04 07:07 UTC, mrerberg commented on src/js/game_screen.ts
> +        cardsField.style.gridTemplateColumns = 'repeat(6, 1fr)'
Лучше манипулировать стилями через классы. А то у тебя стили и css назначает, и js

2022-07-04 07:07 UTC, mrerberg commented on src/js/game_screen.ts
> +newGameButtons.forEach((newGameButton) => {
А может эти элемент сразу сделать ссылками?

2022-07-04 07:07 UTC, mrerberg commented on src/js/game_screen.ts
> +newGameButtons.forEach((newGameButton) => {
Зачем так мудрить с кнопками?

2022-07-04 07:07 UTC, mrerberg commented on src/js/game_screen.ts
> +    let minutes: number | string = Math.floor(totalSeconds / 60)
Старайся по минимуму расширять тип. В данном случае переменная и строкой может быть, и числом. Достаточно числа. К строке ты можешь его приводить тут

```js
minuteSpan.textContent = `0${minutes}`
```

2022-07-04 14:36 UTC, KittySaur commented on src/js/game_screen.ts
> +    let minutes: number | string = Math.floor(totalSeconds / 60)
Здесь на меня тайпскрипт ругается в данном коде, если не указать number and string

```
 if (seconds < 10) {
        seconds = `0${seconds}`
    }
    if (minutes < 10) {
        minutes = `0${minutes}`
    }
```
![image](https://user-images.githubusercontent.com/101009726/177175882-1365f99f-8594-4569-bbea-52b0aab88383.png)

2022-07-04 14:38 UTC, zarina-n commented on src/js/game_screen.ts
> +const cardsField = document.getElementById('cards-field') as HTMLDivElement
![image](https://user-images.githubusercontent.com/101009726/177176280-57486c04-115e-422a-9a61-6c108295da65.png)

Здесь тайпскрипт продолжает ругаться

2022-07-04 16:32 UTC, KittySaur commented on src/js/game_screen.ts
> +        cardsField.style.gridTemplateColumns = 'repeat(6, 1fr)'
Не совсем пойму, как работать через классы. Я могу взять тот же элемент через querySelector('.class')? Потому что я не могу сразу задать стандартный размер через css, он зависит от выбранного уровня

2022-07-05 07:15 UTC, mrerberg commented on src/js/game_screen.ts
> +const cardsField = document.getElementById('cards-field') as HTMLDivElement
Значит, HTMLDivElement | null

2022-07-05 07:16 UTC, mrerberg commented on src/js/game_screen.ts
> +        cardsField.style.gridTemplateColumns = 'repeat(6, 1fr)'
Просто задай стили через класс, а не напрямую через js. classList.add

2022-07-05 07:24 UTC, mrerberg commented on dist/game-screen.html
> +<!doctype html><html lang="ru"><head><meta charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="shortc
dist папки не должно быть в гит. Ее не должно быть в ветке

2022-07-05 07:24 UTC, mrerberg commented on src/js/game_screen.ts
> +    let minutes: number | string = Math.floor(totalSeconds / 60)
Да, потому что ты переприваиваешь переменные. Были числами, стали строками. Надо исправить ситуацию по возможности

2022-07-17 20:06 UTC, merged