Sixth hw
KittySaur/card_game pull request #7
Opened 2022-07-04 18:19 UTC by KittySaur

Добавила тест для функции randomize. 
Не уверена, настколько это правильно, но дублировала ее в отдельный файл js. Провела только тест на проверку длинны нового массива.

2022-07-18 07:28 UTC, mrerberg requested changes

2022-07-18 07:28 UTC, mrerberg commented on src/js/test/randomize.js
> +function randomize(data, toSliceNumber) {
Почему функция рандома может вернуть массив с итоговой длинной больше, чем был входной?

2022-07-18 07:28 UTC, mrerberg commented on src/js/test/randomize.js
> +module.exports = { randomize }
Если пользуемся webpack, мы можем использовать синтаксис import/export, а не такой

2022-07-18 07:28 UTC, mrerberg commented on src/js/test/randomize.test.js
> +const { it, expect } = require('@jest/globals')
Если пользуемся webpack, мы можем использовать синтаксис import/export, а не такой

2022-07-18 07:28 UTC, mrerberg commented on src/js/test/randomize.js
> +function randomize(data, toSliceNumber) {
Может название функции не подходящее?

2022-07-21 23:22 UTC, KittySaur commented on src/js/test/randomize.js
> +function randomize(data, toSliceNumber) {
Навзание поменяла, массив должен быть в 2 раза длиннее, так как все элементы массива дублируются в новом итоговом массиве

2022-07-26 02:51 UTC, merged